[build]
command = "npm run build"
publish = "dist"

# Redirection racine vers /fr/
[[redirects]]
from = "/"
to = "/fr/"
status = 302
force = true

# Cache pour les assets statiques
[[headers]]
for = "/_astro/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
