[build]
command = "npm run build"
publish = "dist"

[functions]
directory = "netlify/functions"

[[redirects]]
from = "/"
to = "/fr"
status = 302
force = true

[[redirects]]
from = "/_astro/*"
to = "/_astro/:splat"
status = 200

[[headers]]
for = "/_astro/*"
[headers.values]
"Cache-Control" = "public, max-age=31536000, immutable"
